redis:
  container_name: bc_challenge_redis
  image: redis:2.8.12
  ports:
   - "0.0.0.0:6379:6379/tcp"

mongo:
  container_name: bc_challenge_mongo
  image: mongo:3.0.8
  ports:
   - "0.0.0.0:27018:27018/tcp"
   - "0.0.0.0:28018:28018/tcp"
  command: mongod --port 27018 --rest --httpinterface --smallfiles
  volumes:
    - ~/.bc-challenge/data/db:/data/db
